name: Test Glob

on:
  push:
    branches: [main]

env:
  RELEASE_VERSION: 1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        with:
          script: |
            const globber = await glob.create('Environments/Sandbox/*.bicep', {followSymbolicLinks: false})
            const files = await globber.glob()
            console.log(files)

      - uses: actions/github-script@v6
        with:
          script: |
            const globber = await glob.create('Environments/Sandbox/*.bicep', {followSymbolicLinks: false})
            for await (const file of globber.globGenerator()) {
              console.log(file);
              console.log(file.split('\\').pop().split('/').pop());
            }
