name: Tests

permissions:
  id-token: write
  contents: read

on:
  push: # TODO: remove

  workflow_dispatch:
    inputs:
      environmentName:
        description: Environment
        type: choice
        options:
          - Dev
          - Test
          - Prod

jobs:
  do_tha_thing:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environmentName || 'Dev' }}
    env:
      AZURE_ENVIRONMENT_TYPE: ${{ github.event.inputs.environmentName || 'Dev' }}

    steps:
      - name: Get Nonexisting var
        shell: python
        run: |
          import os

          required_vars = {
              'AZURE_TENANT_ID': 'your Azure tenant Id (GUID)',
              'AZURE_SUBSCRIPTION_ID': 'your Azure tenant Id (GUID)',
              'AZURE_DEVCENTER': 'the name of your dev center',
              'AZURE_PROJECT': 'the name of your dev center project',
              # 'AZURE_NOT_THERE': 'the name of your dev center notthere'
          }

          required_secrets = {
              'AZURE_CLIENT_ID': 'the app id (or client id) of your service principal',
              'AZURE_CLIENT_SECRET': 'the secret of your service principal'
          }

          if (environment_type := os.getenv('AZURE_ENVIRONMENT_TYPE')) is None:
              print('::error title=Environment not set: AZURE_ENVIRONMENT_TYPE::Please set the environment variable AZURE_ENVIRONMENT_TYPE.')
              exit(1)

          variables = ${{ toJson( vars ) }}
          for k, v in required_vars.items():
              if k not in variables:
                  print(f'::error title=Missing required repository variable: {k}::Please create a new repository variable named {k} with {v}. https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository')
                  exit(1)

          secrets = ${{ toJson( secrets ) }}
          for k, v in required_secrets.items():
              if k not in secrets:
                  print(f'::error title=Missing required environment secret: {k}::Please create a new environment secret for {environment_type} named {k} with {v}. https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-environment')
                  exit(1)

      - name: Echo
        run: |
          echo "AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}"
          echo "AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "AZURE_DEVCENTER: ${{ vars.AZURE_DEVCENTER }}"
          echo "AZURE_PROJECT: ${{ vars.AZURE_PROJECT }}"
          echo "AZURE_ENVIRONMENT_TYPE: ${{ env.AZURE_ENVIRONMENT_TYPE }}"

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Show Project
        run: az devcenter dev project show --dev-center ${{ vars.AZURE_DEVCENTER }} --name ${{ vars.AZURE_PROJECT }}

      - name: List Catalog Items
        run: az devcenter dev catalog-item list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      - name: List Env Types
        run: az devcenter dev environment-type list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      # - name: 'Run az commands'
      #   run: |
      #     az account show
      #     az group list
      #     pwd

      # - name: Echo environment ClientId
      #   run: echo "${{ secrets.AZURE_CLIENT_ID }}"
