name: Tests

permissions:
  id-token: write
  contents: read

on:
  push: # TODO: remove

  workflow_dispatch:
    inputs:
      environmentName:
        description: Environment
        type: choice
        options:
          - Dev
          - Test
          - Prod

jobs:
  do_tha_thing:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environmentName || 'Dev' }}
    env:
      AZURE_ENVIRONMENT_TYPE: ${{ github.event.inputs.environmentName || 'Dev' }}

    steps:
      - name: Get Nonexisting var
        shell: python
        run: |
          import json

          variables = ${{ toJson( vars ) }}

          for k, v in variables.items():
              print(f'{k}: {v}')

          for k in ['AZURE_TENANT_ID', 'AZURE_SUBSCRIPTION_ID', 'AZURE_DEVCENTER', 'AZURE_PROJECT', 'AZURE_NOT_THERE']:
              if k not in variables:
                  print(f'::error title=Missing required repository variable: {k}::Please create a new repository variable named {k}. https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository')
                  exit(1)

      - name: Echo
        run: |
          echo "AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}"
          echo "AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "AZURE_DEVCENTER: ${{ vars.AZURE_DEVCENTER }}"
          echo "AZURE_PROJECT: ${{ vars.AZURE_PROJECT }}"
          echo "AZURE_ENVIRONMENT_TYPE: ${{ env.AZURE_ENVIRONMENT_TYPE }}"

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Show Project
        run: az devcenter dev project show --dev-center ${{ vars.AZURE_DEVCENTER }} --name ${{ vars.AZURE_PROJECT }}

      - name: List Catalog Items
        run: az devcenter dev catalog-item list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      - name: List Env Types
        run: az devcenter dev environment-type list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      # - name: 'Run az commands'
      #   run: |
      #     az account show
      #     az group list
      #     pwd

      # - name: Echo environment ClientId
      #   run: echo "${{ secrets.AZURE_CLIENT_ID }}"
