name: Tests

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: Environment
        type: choice
        options:
          - Dev
          - Test
          - Prod

jobs:
  dothing:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environmentName }}

    steps:
      - name: Echo environmentName
        run: echo "${{ github.event.inputs.environmentName }}"

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List Projects
        run: az devcenter dev project list -d TutorialDevCenter

      # - name: 'Run az commands'
      #   run: |
      #     az account show
      #     az group list
      #     pwd

      # - name: Echo environment ClientId
      #   run: echo "${{ secrets.AZURE_CLIENT_ID }}"
