name: Tests

permissions:
  id-token: write
  contents: read

on:
  push: # TODO: remove

  workflow_dispatch:
    inputs:
      environmentName:
        description: Environment
        type: choice
        options:
          - Dev
          - Test
          - Prod

jobs:
  config:
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  do_tha_thing:
    runs-on: ubuntu-latest
    needs: config
    environment: ${{ needs.config.outputs.type }}
    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}

    steps:
      - name: Echo
        run: |
          echo "AZURE_PROJECT: ${{ vars.AZURE_PROJECT }}"
          echo "AZURE_DEVCENTER: ${{ vars.AZURE_DEVCENTER }}"
          echo "AZURE_CATALOG: ${{ vars.AZURE_CATALOG }}"
          echo "AZURE_CATALOG_ITEM: ${{ vars.AZURE_CATALOG_ITEM }}"
          echo "AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}"
          echo "ENVIRONMENT_TYPE: ${{ env.ENVIRONMENT_TYPE }}"
          echo "ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}"

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Show Project
        run: az devcenter dev project show --dev-center ${{ vars.AZURE_DEVCENTER }} --name ${{ vars.AZURE_PROJECT }}

      - name: List Catalog Items
        run: az devcenter dev catalog-item list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      - name: List Env Types
        run: az devcenter dev environment-type list --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }}

      # - name: 'Run az commands'
      #   run: |
      #     az account show
      #     az group list
      #     pwd

      # - name: Echo environment ClientId
      #   run: echo "${{ secrets.AZURE_CLIENT_ID }}"
